import os
import json
from typing import TypedDict, Dict, Any, List
from langgraph.graph import StateGraph, START, END
from langchain_groq import ChatGroq
from src.rag import StrategyRAG

# State Definition
# This dictionary stores data as our agent moves from step to step
class PlayerAgentState(TypedDict):
    player_data: dict                       # The data the user entered in the app
    churn_proba: float                      # Risk percentage between 0.0 and 1.0
    is_churn: bool                          # True if risk is high, False if low
    retrieved_strategies: list              # List of strategies found from our RAG
    structured_evaluation: dict             # Final plan generated by the LLM
    error: str                              # Stores any errors that happen

# Load our local Strategy Database (FAISS)
rag_database = StrategyRAG()

# Node 1: AI Machine Learning Prediction
def predict_risk(state: PlayerAgentState, pipeline) -> PlayerAgentState:
    """ 
    Step 1: Uses our Scikit-Learn Machine Learning model to guess 
    if the player will churn (quit the game).
    """
    try:
        import pandas as pd
        
        data_frame = pd.DataFrame([state["player_data"]])
        
        prediction_result = pipeline.predict(data_frame)[0]
        probability = pipeline.predict_proba(data_frame)[0][1]
        
        state["is_churn"] = (prediction_result == 1)
        state["churn_proba"] = float(probability)
        
    except Exception as e:
        state["error"] = "Error in prediction: " + str(e)
    
    return state

# Node 2: Knowledge Retrieval (RAG)
def retrieve_knowledge(state: PlayerAgentState) -> PlayerAgentState:
    """ 
    Step 2: If the player is at risk of quitting, look up good 
    strategies from our database.
    """
    # If they are not going to quit, we don't need strategies
    if state["is_churn"] == False:
        state["retrieved_strategies"] = []
        return state
        
    player_info = state["player_data"]
    
    # Create a nice sentence describing the player
    search_query = (
        f"Age {player_info['Age']}, Level {player_info['PlayerLevel']}, "
        f"PlayTime {player_info['PlayTimeHours']} hours, "
        f"Purchases: {player_info['InGamePurchases']}"
    )
            
    try:
        # Search our FAISS database
        strategies = rag_database.retrieve_strategies(search_query, number_of_results=2)
        state["retrieved_strategies"] = strategies
    except Exception as e:
        state["error"] = "Error searching strategies: " + str(e)
        state["retrieved_strategies"] = []
        
    return state

# 
# Node 3: LLM Plan Generation
def generate_plan(state: PlayerAgentState) -> PlayerAgentState:
    """ 
    Step 3: Uses ChatGroq (LLM) to write a customized retention plan.
    """
    # If the player is safe, return a standard positive message
    if state["is_churn"] == False:
        state["structured_evaluation"] = {
            "Summary": "Player is happy and active.",
            "Analysis": "Low risk of quitting.",
            "Plan": "Keep doing what you are doing. No action needed.",
            "Refs": "None",
            "Disclaimer": "Auto-response for safe players."
        }
        return state

    try:
        # Get the API Key from the computer
        my_api_key = os.environ.get("GROQ_API_KEY")
        if my_api_key == None:
            state["error"] = "No GROQ_API_KEY found!"
            return state
            
        # Connect to Groq AI
        ai_chatbot = ChatGroq(
            temperature=0.7, 
            groq_api_key=my_api_key, 
            model_name="llama-3.1-8b-instant"
        )
        
        # Write our instruction for the AI
        ai_prompt = f"""
        You are a Game Expert. Look at this player struggling:
        {json.dumps(state['player_data'])}
        
        Risk of quitting: {state['churn_proba'] * 100}%
        
        Good strategies to help them:
        {json.dumps(state['retrieved_strategies'])}
        
        Write a plan using EXACTLY this JSON structure. Do not return anything except json:
        {{
            "Summary": "A very short description of the player.",
            "Analysis": "Why they are quitting.",
            "Plan": "What we should do to fix it.",
            "Refs": "Mention any strategies you used.",
            "Disclaimer": "Warning about using AI safely."
        }}
        """
        
        # Send the message to Groq
        groq_reply = ai_chatbot.invoke(ai_prompt)
        text_reply = groq_reply.content
        
        # clean the text to just get the JSON part
        if "```json" in text_reply:
            text_reply = text_reply.split("```json")[1].split("```")[0].strip()
        elif "```" in text_reply:
            text_reply = text_reply.split("```")[1].strip()
            
        # Convert text into a real python dictionary
        structured_plan = json.loads(text_reply)
        state["structured_evaluation"] = structured_plan
        
    except Exception as e:
        state["error"] = "AI Error: " + str(e)
        state["structured_evaluation"] = {}

    return state

# Build The LangGraph Workflow
def build_agent_graph(pipeline):
    """
    Connects our 3 steps together into a workflow graph!
    """
    graph = StateGraph(PlayerAgentState)
    
    # We need a small helper to pass the pipeline into our first step
    def starting_node(state: PlayerAgentState):
        return predict_risk(state, pipeline)
        
    # 1. Add all our steps (nodes) to the graph
    graph.add_node("predict_risk", starting_node)
    graph.add_node("retrieve_knowledge", retrieve_knowledge)
    graph.add_node("generate_plan", generate_plan)
    
    # 2. Tell the graph what order to run them in (edges)
    graph.add_edge(START, "predict_risk")
    graph.add_edge("predict_risk", "retrieve_knowledge")
    graph.add_edge("retrieve_knowledge", "generate_plan")
    graph.add_edge("generate_plan", END)
    
    return graph.compile()